version: '3'
services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules/
    ports:
      - "127.0.0.1:8080:8080"
  products-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
    working_dir: /internal/products
    ports:
      - "127.0.0.1:9090:9090"
    env_file:
      - .env
